# Dependabot configuration for SysPilot
# Automatically creates PRs for dependency updates

version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5
    assignees:
      - "maintainer-username"  # Replace with actual maintainer
    reviewers:
      - "maintainer-username"  # Replace with actual maintainer
    labels:
      - "dependencies"
      - "python"
      - "automated"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
      include: "scope"
    ignore:
      # Ignore major version updates for critical dependencies
      - dependency-name: "PyQt5"
        update-types: ["version-update:semver-major"]
      - dependency-name: "pytest"
        update-types: ["version-update:semver-major"]
    groups:
      # Group pytest-related dependencies
      testing:
        patterns:
          - "pytest*"
          - "coverage"

      # Group linting and formatting tools
      code-quality:
        patterns:
          - "black"
          - "isort"
          - "flake8*"
          - "pylint"
          - "mypy"
          - "bandit"

      # Group documentation dependencies
      documentation:
        patterns:
          - "sphinx*"
          - "pydocstyle"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 3
    assignees:
      - "maintainer-username"  # Replace with actual maintainer
    reviewers:
      - "maintainer-username"  # Replace with actual maintainer
    labels:
      - "dependencies"
      - "github-actions"
      - "automated"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"

  # Pre-commit hooks
  - package-ecosystem: "pip"
    directory: "/.pre-commit-hooks"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 2
    assignees:
      - "maintainer-username"  # Replace with actual maintainer
    labels:
      - "dependencies"
      - "pre-commit"
      - "automated"
    commit-message:
      prefix: "chore(hooks)"
      include: "scope"
