name: ✨ Feature Request
description: Suggest a new feature or enhancement for SysPilot
title: "[FEATURE] Brief description of the feature"
labels: ["enhancement", "needs-triage"]

body:
  - type: markdown
    attributes:
      value: |
        ## ✨ Feature Request

        Thank you for suggesting a new feature! Please fill out the form below to help us understand your idea.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues and discussions to ensure this feature hasn't been requested before
          required: true
        - label: I have read the [Contributing Guidelines](CONTRIBUTING.md)
          required: true
        - label: This feature aligns with SysPilot's goals and scope
          required: true

  - type: textarea
    id: feature-summary
    attributes:
      label: 🎯 Feature Summary
      description: A clear and concise description of the feature you'd like to see
      placeholder: What feature would you like to be added?
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: 🤔 Problem Statement
      description: What problem does this feature solve? What use case does it address?
      placeholder: Describe the problem or need this feature would address...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: 💡 Proposed Solution
      description: Describe the solution you'd like to see implemented
      placeholder: How would you like this feature to work?
    validations:
      required: true

  - type: textarea
    id: alternative-solutions
    attributes:
      label: 🔄 Alternative Solutions
      description: Describe any alternative solutions or workarounds you've considered
      placeholder: What other approaches could solve this problem?

  - type: dropdown
    id: feature-category
    attributes:
      label: 📂 Feature Category
      description: Which area of SysPilot does this feature relate to?
      options:
        - System Monitoring
        - Cleanup and Optimization
        - User Interface
        - Cross-Platform Support
        - Performance
        - Security
        - Configuration
        - Automation
        - Reporting
        - API/Integration
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: ⭐ Priority Level
      description: How important is this feature to you?
      options:
        - Critical - Essential for my workflow
        - High - Would significantly improve my experience
        - Medium - Nice to have
        - Low - Minor improvement
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: 🔧 Expected Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Simple - Minor change or addition
        - Medium - Moderate development effort
        - Complex - Significant development effort
        - Unknown - Not sure about implementation complexity

  - type: textarea
    id: user-stories
    attributes:
      label: 👤 User Stories
      description: Describe how users would interact with this feature
      placeholder: |
        As a [type of user], I want [functionality] so that [benefit].

        Example scenarios:
        - When I...
        - Then I should be able to...

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: ✅ Acceptance Criteria
      description: What would need to be true for this feature to be considered complete?
      placeholder: |
        - [ ] Criteria 1
        - [ ] Criteria 2
        - [ ] Criteria 3

  - type: textarea
    id: mockups-wireframes
    attributes:
      label: 🎨 Mockups/Wireframes
      description: If this is a UI feature, please provide mockups or wireframes
      placeholder: Drag and drop images here or describe the UI layout

  - type: textarea
    id: technical-considerations
    attributes:
      label: ⚙️ Technical Considerations
      description: Any technical aspects, dependencies, or constraints to consider?
      placeholder: Performance requirements, compatibility needs, security considerations, etc.

  - type: checkboxes
    id: platforms
    attributes:
      label: 🖥️ Target Platforms
      description: Which platforms should this feature support?
      options:
        - label: Linux
        - label: Windows
        - label: macOS
        - label: All platforms

  - type: textarea
    id: additional-context
    attributes:
      label: 📋 Additional Context
      description: Add any other context, examples, or references about the feature request
      placeholder: Links to similar features in other tools, research, etc.

  - type: checkboxes
    id: contribution
    attributes:
      label: 🤝 Contribution
      description: Would you be interested in contributing to this feature?
      options:
        - label: I would like to implement this feature myself
        - label: I can help with testing once implemented
        - label: I can provide feedback during development
        - label: I can help with documentation
